Updates to align with updates to tidyselect and dplyr functionality
pharmaverse/logrx pull request #174
Opened 2023-05-09 14:38 UTC by kodesiba

### Thank you for your Pull Request! 

We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the logrx codebase remains robust and consistent.  

### The spirit of logrx

While many packages to facilitate the logging of code already exist in the R ecosystem, it is hard to find a solution that works well for clinical programming applications. Many logging implementations are more implicit and rely on user input to create the log for the execution of a script. While this is useful for logging specific events of an application, in clinical programming a log has a set purpose.

logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well as the environment that it happened in. We set out to create a flexible logging utility that could provide the necessary information to anyone reviewing the code execution so they can recreate the execution environment and run the code for themselves. Please make sure your Pull Request meets this **spirit of logrx**.

Please check off each taskbox as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `dev` branch until you have checked off each task.

- [ ] The spirit of logrx is met in your Pull Request
- [ ] Check that your Pull Request is targeting the dev branch, Pull Requests to master should use the [Release Pull Request Template](https://github.com/pharmaverse/logrx/blob/main/.github/PULL_REQUEST_TEMPLATE/release.md)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests.  Remember to remove any configured log objects at the end of every test using `log_remove()`.
- [ ] Creation/updates to relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "Reference" page.
- [ ] Update NEWS.md if the changes pertain to a user-facing function (i.e. it has an @export tag) or documentation aimed at users (rather than developers)
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

Closes #172

2023-05-22 13:30 UTC, parmsam-pfizer commented
Do we need `distinct(across())` or `distinct(across(.cols = everything(), fns = NULL))`? It looks like `distinct()` would suffice since it gets distinctness using all variables in the dataframe. Alternatively, if we need to include the tidyselect part then this works: `distinct(across(.cols = everything()))`
https://github.com/pharmaverse/logrx/pull/174/files#diff-be75f6398b6213cfe50e1318d8488ba76de0c0cefddbaae032844bad84fe8492R200-R201

2023-05-22 16:10 UTC, kodesiba commented
> 

@nicholas-masel  any thoughts here?  Not fully sure how everything is working in this function and I think you were the one who wrote this part.

2023-06-05 15:13 UTC, bms63 commented on NEWS.md
> + - hotfix for update to `across()` and `.data$var` updates in source packages (#172)
mention requirement for dplyr

2023-06-12 19:50 UTC, nicholas-masel requested changes
@parmsam-pfizer is correct.  This can just use distinct() without across().

2023-06-15 16:07 UTC, bms63 approved these changes

2023-06-15 16:08 UTC, merged